### PR TITLE
Print IP:Port of SSC (WebUI)

### PR DESCRIPTION
**Pull request by quake101**
Print to console the IP:Port the front/app.py has started on.

### CODE REVIEW

**Review by smart-underworld — COMMENTED** [review]
With this code, won't it just print 127.0.0.1 or 0.0.0.0?

**Comment by quake101** [comment]
Currently when front/app.py starts it only prints out what configuration file it's loaded. With this PR, it will print out that the front/app.py has started and on what IP:PORT it started on. (Yes, it's pulling these values from the configuration file). This will give the user a little more feedback.

An improvement would be to list what IP's falcon as successfully binded to. (Not sure this is possible, but I will look into it)

**Comment by smart-underworld** [comment]
Yes that's possible and preferable. I have that in my private snapshot. You
can Google for it. If unsuccessful, I can try to dig that up.

**Comment by quake101** [comment]
@smart-underworld , I wasn't successful. Would you mind sharing your solution?

**Comment by smart-underworld** [comment]
Here's my strategy:

def get_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.settimeout(0)
    try:
        # doesn't even have to be reachable
        s.connect(('10.254.254.254', 1))
        IP = s.getsockname()[0]
    except Exception:
        IP = '127.0.0.1'
    finally:
        s.close()
    return IP

**Comment by quake101** [comment]
I've updated the pull request. This will find the IP address of the machine if 0.0.0.0 is supplied.

**Pull request merged**
