### PR TITLE
Fix typo in device/seestar_device.py

### PR DESCRIPTION
**Pull request by quake101**
Fix typo pointed out by Allen Tian on Discord.

### CODE REVIEW

**Review by erewhon — COMMENTED** [review]
Are we 100% sure?   The parameter array is also in the Bruno file.  This gets passed on to the Seestar.   Is it expected a map or an array?

**Comment by YungKC** [comment]
I am not with my computer, but be careful with param names/values that are
passed to Seestar. There are mis-spellings but are expected by the firmware.

**Comment by quake101** [comment]
Ok, this needs more testing. I'm not 100% sure, but it did look weird to me.

**Comment by erewhon** [comment]
Just let us know if it's ok.

**Comment by quake101** [comment]
I did some more testing and it's not a typo.

**Pull request closed without merging**
