### PR TITLE
[DONT MERGE YET] 3ppa completion

### PR DESCRIPTION
**Pull request by bguthro**
If 3PPA completes with 99% - mark it as complete

### CODE REVIEW

**Comment by YungKC** [comment]
Was it because we stopped 3ppa intentionally after 99%?

**Comment by bguthro** [comment]
> What I would prefer is to take the returned state of complete or failed literally, and not use 99.0% as the threshold. I was waiting for your logs to see why it reported a failed state after 99.0%.

Unclear. I'll try to find the logs.

**Comment by smart-underworld** [comment]
Btw, this PR would not have fixed the red badge error in the page because that's from the event state for 3PPA. Added logic will be needed.

**Comment by bguthro** [comment]
[alpyca.log](https://github.com/user-attachments/files/17509581/alpyca.log)

**Comment by bguthro** [comment]
> Btw, this PR would not have fixed the red badge error in the page because that's from the event state for 3PPA. Added logic will be needed.

ACK. Will decline then, and continue discussion in Slack

**Pull request closed without merging**
