### PR TITLE
Clean up Retry logic

### PR DESCRIPTION
**Pull request by rrowley42**
The retry logic in seestar_device was cleaned up.

Restart logic was added if shutdown has been sent

In telescope.py,  moveaxis had a small bug

### CODE REVIEW

**Review by smart-underworld — COMMENTED** [review]
Question about shutdown logic change. This was for users to shutdown and thus power off Seestar. Why is there logic to start seestar device again?

**Comment by rrowley42** [comment]
WileEyte was cycling the Seestar and didn’t want to also have to cycle Seestar_alp.   I can remove it if you don’t think it is good enough use case.

**Comment by YungKC** [comment]
It's probably better to interpret the shutdown request as to end the night
session, and having the Seestar powered off. Ideally leave the app alive
but with a log or message stating the device has been shutdown.

To power up Seestar again, that would be a new seestar_alp session.

**Comment by rrowley42** [comment]
Ok, I’m good with that.

 

Do you accept that pull and then I submit another pull for this change?

 

Or do you reject the pull?  

 

Rod

**Comment by rrowley42** [comment]
I thought about putting some comments in moveaxis in telescope.py to indicate the direction.

0 is right

90 is up

180 is left

270 is down

 

Took awhile to figure out.

**Comment by YungKC** [comment]
It's best practice to submit another PR to replace the earlier one.

**Comment by rrowley42** [comment]
Ok, will do.

**Pull request merged**
